import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import Brand from '../components/Brand';
import Sparkline from '../components/Sparkline';
import StatCard from '../components/StatCard';
import { BellIcon, BoltIcon, ChartIcon, CheckIcon, GearIcon, HomeIcon, PauseIcon, PlayIcon, RefreshIcon, ShieldIcon, SwapIcon, UserIcon, WalletIcon } from '../components/Icons';
import { api, humanizeError, session } from '../lib/api';
import type { Entitlement, Execution, Operations, Performance, Position, ReferralSummary, TradingConfig, User } from '../types';

const money=(n:unknown)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0);
// Market prices need their own precision; USD balances and PnL stay at cents.
const marketPrice=(value:unknown)=>{
  if(value==null || value==='') return '—';
  const n=Number(value);
  if(!Number.isFinite(n) || n<=0) return '—';
  const abs=Math.abs(n);
  const digits=abs<0.0001?10:abs<0.01?8:abs<1?6:abs<1000?4:2;
  return new Intl.NumberFormat('en-US',{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(n);
};
const pct=(n:unknown)=>`${Number(n||0).toFixed(2)}%`;
const num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:0};
const date=(v:unknown)=>{if(!v)return '—'; const n=typeof v==='number'&&v<1e12?v*1000:v; const d=new Date(n as string|number); return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('es-MX',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(d)};
const side=(p:Position)=>String(p.side||p.direction||'—').toUpperCase();
const symbol=(p:Position)=>String(p.symbol||'—').replace(/[_-]/g,'/');
const pnl=(p:Position)=>p.net_pnl!=null?num(p.net_pnl):num(p.realized_pnl)-num(p.entry_fee)-num(p.exit_fee)+num(p.funding_pnl);

export default function DashboardPage({user,isAdmin,onOpenAdmin,onOpenSubscription,onOpenActivity,onSignedOut}:{user:User;isAdmin:boolean;onOpenAdmin:()=>void;onOpenSubscription:()=>void;onOpenActivity:()=>void;onSignedOut:()=>void}){
  const [config,setConfig]=useState<TradingConfig|null>(null); const [exec,setExec]=useState<Execution|null>(null); const [perf,setPerf]=useState<Performance|null>(null); const [ops,setOps]=useState<Operations>({open:[],closed:[]}); const [ent,setEnt]=useState<Entitlement|null>(null);
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(''); const [drawer,setDrawer]=useState(false);
  const [capital,setCapital]=useState(''); const [apiKey,setApiKey]=useState(''); const [apiSecret,setApiSecret]=useState('');
  const [showNotifications,setShowNotifications]=useState(false); const [showProfile,setShowProfile]=useState(false); const [referrals,setReferrals]=useState<ReferralSummary|null>(null); const [copied,setCopied]=useState(false);
  const topActions=useRef<HTMLDivElement|null>(null);

  const load=useCallback(async(silent=false)=>{
    if(!silent)setLoading(true);
    setError('');
    const requests = [
      ['config', api.config()],['execution', api.execution()],['performance', api.performance()],['operations', api.operations()],['entitlement', api.entitlement()],['referrals', api.referrals()],
    ] as const;
    const results=await Promise.allSettled(requests.map(([,promise])=>promise)); const failures:string[]=[];
    results.forEach((result,index)=>{const name=requests[index][0];if(result.status==='rejected'){failures.push(`${name}: ${humanizeError(result.reason)}`);return;}if(name==='config'){const c=result.value as TradingConfig;setConfig(c);setCapital(c.operating_capital>0?String(c.operating_capital):'');}else if(name==='execution')setExec(result.value as Execution);else if(name==='performance')setPerf(result.value as Performance);else if(name==='operations')setOps(result.value as Operations);else if(name==='entitlement')setEnt(result.value as Entitlement);else if(name==='referrals')setReferrals(result.value as ReferralSummary);});
    if(failures.length)setError(failures.join(' · ')); if(!session.get())onSignedOut(); setLoading(false);
  },[onSignedOut]);
  useEffect(()=>{load(); const id=window.setInterval(()=>load(true),15000); return()=>clearInterval(id)},[load]);
  useEffect(()=>{const close=(e:MouseEvent)=>{if(topActions.current&&!topActions.current.contains(e.target as Node)){setShowNotifications(false);setShowProfile(false)}};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);

  const mode=config?.execution_mode||'demo'; const enabled=Boolean(config?.trading_enabled); const verified=Boolean(config?.coinw_verified);
  const available=mode==='demo'?(config?.demo_available_equity??0):(exec?.available_equity??config?.live_available_equity??0);
  const equity=useMemo(()=>{let cur=perf?.capital||config?.operating_capital||0;const values=[cur];[...ops.closed].reverse().forEach(p=>{cur+=pnl(p);values.push(cur)});return values},[ops.closed,perf?.capital,config?.operating_capital]);
  const notifications=useMemo(()=>{
    const items:{tone:'ok'|'warn'|'info';title:string;text:string}[]=[];
    if(!config?.coinw_configured)items.push({tone:'warn',title:'CoinW pendiente',text:'Guarda tu API Key y API Secret.'});
    else if(!verified)items.push({tone:'warn',title:'Verificación requerida',text:'Pulsa “Verificar conexión” antes de configurar capital.'});
    else items.push({tone:'ok',title:'CoinW verificado',text:'Las credenciales fueron validadas correctamente.'});
    items.push({tone:enabled?'ok':'info',title:`Trading ${enabled?'activo':'pausado'}`,text:`Modo actual: ${mode.toUpperCase()}.`});
    if(ops.open.length)items.push({tone:'info',title:'Operaciones activas',text:`Hay ${ops.open.length} posición${ops.open.length===1?'':'es'} abierta${ops.open.length===1?'':'s'} en ${mode.toUpperCase()}.`});
    return items;
  },[config?.coinw_configured,verified,enabled,mode,ops.open.length]);

  async function save(partial:Partial<{execution_mode:'demo'|'live';trading_enabled:boolean;operating_capital:number;coinw_api_key:string;coinw_api_secret:string}>, action='save'){
    if(!config)return;setBusy(action);setError('');setNotice('');
    try{
      const body:{execution_mode:'demo'|'live';trading_enabled:boolean;operating_capital?:number;coinw_api_key?:string;coinw_api_secret?:string}={execution_mode:partial.execution_mode??config.execution_mode,trading_enabled:partial.trading_enabled??config.trading_enabled};
      if(partial.operating_capital!==undefined)body.operating_capital=partial.operating_capital;
      if(partial.coinw_api_key!==undefined){body.coinw_api_key=partial.coinw_api_key;body.coinw_api_secret=partial.coinw_api_secret||'';}
      await api.saveConfig(body);setNotice(action==='credentials'?'Credenciales guardadas. Ahora verifica la conexión con CoinW.':'Configuración actualizada correctamente.');setApiKey('');setApiSecret('');await load(true);
    }catch(err){setError(humanizeError(err));}finally{setBusy('')}
  }
  async function testCoinW(){setBusy('coinw-test');setError('');setNotice('');try{const r=await api.testCoinW();setNotice(`CoinW verificado. Saldo LIVE disponible: ${money(r.available_equity)} · DEMO: ${money(r.demo_equity)}`);await load(true)}catch(err){setError(humanizeError(err))}finally{setBusy('')}}
  async function disconnect(){setBusy('disconnect');setError('');try{await api.deleteCredentials();setNotice('Credenciales CoinW eliminadas. El capital y el trading quedan bloqueados hasta una nueva verificación.');await load(true)}catch(err){setError(humanizeError(err))}finally{setBusy('')}}
  async function activateTrial(){setBusy('trial');setError('');try{await api.activateTrial();setNotice('Prueba LIVE activada.');await load(true)}catch(err){setError(humanizeError(err))}finally{setBusy('')}}
  async function switchMode(next:'demo'|'live'){if(next==='live'&&!config?.live_allowed)return;await save({execution_mode:next,trading_enabled:false},'mode')}
  async function logout(){try{await api.logout()}catch{}session.clear();onSignedOut()}

  const capitalValue=Number(capital); const capitalValid=Number.isFinite(capitalValue)&&capitalValue>0&&capitalValue<=(available||0); const totalPositionCount=ops.open.length;
  if(loading&&!config)return <div className="app-loader"><div className="loader-ring"/><strong>KAELEON</strong><span>Cargando tu panel…</span></div>;

  return <div className="dashboard-shell">
    <aside className={`sidebar ${drawer?'open':''}`}><div className="sidebar-brand"><Brand/></div><nav><a href="#inicio"><HomeIcon/>Dashboard</a><a className="active" href="#ejecucion"><BoltIcon/>Ejecución</a><button className="sidebar-activity-link" onClick={onOpenActivity}><ChartIcon/>Monitor en vivo</button><a href="#operaciones"><SwapIcon/>Operaciones</a><a href="#rendimiento"><ChartIcon/>Rendimiento</a><a href="#configuracion"><GearIcon/>Configuración</a><button className="sidebar-subscription-link" onClick={onOpenSubscription}><WalletIcon/>Planes / Suscripción</button><a href="#referidos"><UserIcon/>Referidos</a>{isAdmin&&<button className="sidebar-admin-link" onClick={onOpenAdmin}><ShieldIcon/>Administración</button>}</nav><div className="side-promo"><div className="lizard-orb">K</div><h3>KAELEON</h3><strong>Tu aliado en el trading</strong><p>Tecnología, disciplina y gestión de riesgo conectadas a tu cuenta.</p><span><i/>Trading {enabled?'Activo':'Pausado'}</span></div></aside>
    {drawer&&<button className="drawer-backdrop" onClick={()=>setDrawer(false)} aria-label="Cerrar menú"/>}
    <div className="main-column">
      <header className="topbar"><button className="mobile-menu" onClick={()=>setDrawer(true)}>☰</button><div className="market-strip"><MarketChip icon="₿" label="BTC/USDT" status="KAELEON AUTO"/><MarketChip icon="Ξ" label="ETH/USDT" status="KAELEON AUTO"/><MarketChip icon="S" label="SOL/USDT" status="KAELEON AUTO"/><MarketChip icon="◆" label="Mercados" status={`${exec?.markets_scanned||0} escaneados`}/></div><div className="top-actions" ref={topActions}><div className="action-wrap"><button className="icon-action" onClick={()=>{setShowNotifications(v=>!v);setShowProfile(false)}} aria-label="Notificaciones"><BellIcon/>{notifications.some(n=>n.tone==='warn')&&<i/>}</button>{showNotifications&&<div className="top-popover notifications-popover"><div className="popover-head"><strong>Notificaciones</strong><span>{notifications.length}</span></div>{notifications.map((n,i)=><div className={`notification-item ${n.tone}`} key={i}><b>{n.title}</b><small>{n.text}</small></div>)}</div>}</div><div className="action-wrap"><button className="avatar avatar-button" onClick={()=>{setShowProfile(v=>!v);setShowNotifications(false)}} aria-label="Cuenta"><UserIcon/></button>{showProfile&&<div className="top-popover profile-popover"><strong>Mi cuenta</strong><span>{user.phone||'Usuario KAELEON'}</span><small>Rol: {user.role||'USER'} · Plan: {user.plan||'TRIAL'}</small><div className="profile-status"><i className={user.telegram_verified?'ok':''}/>Telegram {user.telegram_verified?'verificado':'pendiente'}</div><button className="subscription-profile-button" onClick={onOpenSubscription}>Planes / Suscripción</button>{isAdmin&&<button className="admin-profile-button" onClick={onOpenAdmin}>Abrir administración</button>}<button onClick={logout}>Cerrar sesión</button></div>}</div><div className="welcome"><span>Bienvenido</span><strong>{user.phone||'Usuario KAELEON'}</strong></div><button className="logout-mini" onClick={logout}>Salir</button></div></header>
      <main className="content" id="ejecucion">
        <section className="page-heading"><div className="heading-icon"><BoltIcon/></div><div><h1>Ejecución</h1><p>Configura CoinW, selecciona DEMO o LIVE y deja que KAELEON gestione la ejecución.</p></div><button className="refresh-btn" onClick={()=>load()}><RefreshIcon/>Actualizar</button></section>
        {error&&<div className="banner banner-error">{error}</div>}{notice&&<div className="banner banner-success">{notice}</div>}{exec?.last_rejection&&<div className="info-box">Última evaluación: {humanizeError(new Error(exec.last_rejection))}</div>}
        <section className="config-grid" id="configuracion">
          <article className="panel coinw-panel"><PanelTitle icon={<WalletIcon/>} title="Cuenta CoinW" badge={verified?'Verificada':config?.coinw_configured?'Pendiente':'Sin conectar'} badgeTone={verified?'green':config?.coinw_configured?'amber':'gray'}/><div className="coinw-logo"><span>CW</span><strong>CoinW</strong></div><label>API Key<input value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={config?.coinw_api_key||'Pega tu API Key'}/></label><label>API Secret<input type="password" value={apiSecret} onChange={e=>setApiSecret(e.target.value)} placeholder={config?.coinw_configured?'••••••••••••••••':'Pega tu API Secret'}/></label><button className="verify-btn" disabled={!config?.coinw_configured||busy==='coinw-test'} onClick={testCoinW}><CheckIcon/>{busy==='coinw-test'?'Comprobando…':verified?'Volver a verificar':'Verificar conexión'}</button><div className="coinw-actions">{apiKey&&apiSecret&&<button className="secondary-btn" disabled={!!busy} onClick={()=>save({coinw_api_key:apiKey,coinw_api_secret:apiSecret},'credentials')}>Guardar credenciales</button>}{config?.coinw_configured&&<button className="danger-outline" disabled={!!busy||enabled} onClick={disconnect}>Desconectar</button>}</div><div className="credential-rule"><ShieldIcon/><span>DEMO y LIVE requieren credenciales CoinW verificadas. DEMO usa mercado real, pero nunca envía órdenes.</span></div></article>
          <article className={`panel capital-panel ${!verified?'panel-locked':''}`}><PanelTitle icon={<ShieldIcon/>} title="Capital operativo" badge={mode.toUpperCase()} badgeTone={mode==='demo'?'blue':'green'}/><div className="capital-summary"><div><span>Capital configurado</span><strong>{money(config?.operating_capital)}</strong></div><div className="capital-ring"><span>{available?Math.min(100,Math.round((config?.operating_capital||0)/Math.max(available,1)*100)):0}%</span><small>asignado</small></div><div><span>{mode==='demo'?'Saldo DEMO':'Disponible CoinW'}</span><strong className="green">{money(available)}</strong></div></div>{!verified?<div className="locked-message"><ShieldIcon/><strong>Capital bloqueado</strong><span>Guarda y verifica primero tu API Key y API Secret de CoinW.</span></div>:<label>Capital para KAELEON<div className="capital-input"><span>$</span><input type="number" min={config?.minimum_operating_capital||3} max={available} step="0.01" value={capital} onChange={e=>setCapital(e.target.value)}/><button onClick={()=>save({operating_capital:capitalValue},'capital')} disabled={!!busy||!capitalValid}>Guardar</button></div>{capital&&capitalValue>available&&<small className="field-error">No puede superar {money(available)}.</small>}</label>}<div className="info-box"><strong>{mode==='demo'?'Saldo DEMO con ganancias y pérdidas':'LIVE: saldo real CoinW'}</strong><p>{mode==='demo'?'Datos reales de CoinW y ejecución simulada a 10x. El resultado neto de cada operación actualiza tu saldo. Al asignar el 100%, el capital operativo acompaña el saldo.':'El capital se valida contra el saldo USDT disponible de CoinW antes de guardarse.'}</p></div><div className="backend-rules"><span>Mercados <b>Automático</b></span><span>Timeframes <b>Internos</b></span><span>Leverage <b>10x</b></span></div></article>
          <article className="panel trading-panel"><PanelTitle icon={<BoltIcon/>} title="Modo de trading"/><div className="mode-picker"><button className={mode==='demo'?'selected':''} disabled={!!busy} onClick={()=>switchMode('demo')}><ShieldIcon/><strong>DEMO</strong><span>Cuenta virtual · mercado real · 10x</span></button><button className={`${mode==='live'?'selected live':''} ${!config?.live_allowed?'locked':''}`} disabled={!!busy||!config?.live_allowed} onClick={()=>switchMode('live')}><span className="lock">{config?.live_allowed?'●':'🔒'}</span><strong>LIVE</strong><span>{config?.live_allowed?'Saldo y ejecución reales':'Requiere acceso LIVE'}</span></button></div>{!config?.live_allowed&&<div className="live-access-actions"><button className="trial-btn" disabled={!!busy} onClick={activateTrial}>{busy==='trial'?'Activando…':'Activar prueba LIVE'}</button><button className="plans-btn" onClick={onOpenSubscription}>Ver planes LIVE</button></div>}<button className="start-btn" disabled={!!busy||enabled||!verified||!config?.operating_capital} onClick={()=>save({trading_enabled:true},'start')}><PlayIcon/>Activar {mode.toUpperCase()}</button><button className="pause-btn" disabled={!!busy||!enabled} onClick={()=>save({trading_enabled:false},'pause')}><PauseIcon/>Pausar Trading</button><div className="warning-box">Las estadísticas y operaciones se mantienen separadas por modo. Al cambiar entre DEMO y LIVE, el dashboard cambia automáticamente al historial de ese modo.</div></article>
        </section>
        <section className={`engine-bar ${enabled?'active':''}`}><div className="engine-title"><span className="engine-icon">◉</span><div><small>Estado del motor</small><strong>{exec?.status||'PAUSADO'}</strong></div></div><EngineMetric label="Modo" value={(exec?.mode||mode).toUpperCase()}/><EngineMetric label="CoinW" value={verified?'VERIFICADO':'NO VERIFICADO'}/><EngineMetric label="Datos" value={exec?.last_market_at&&Date.now()-exec.last_market_at<30000?'EN VIVO':'SIN DATOS RECIENTES'}/><EngineMetric label="Capital" value={money(exec?.configured_capital)}/><EngineMetric label="Posiciones" value={String(totalPositionCount)}/><div className="engine-spark"><Sparkline values={equity}/></div></section>
        <section className="analytics-grid" id="rendimiento">
          <article className="panel chart-panel"><div className="chart-header"><div><span className="asset-badge">K</span><strong>Curva de capital · {mode.toUpperCase()}</strong><em>{money(perf?.current_capital)}</em><b className={(perf?.pnl||0)>=0?'green':'red'}>{(perf?.pnl||0)>=0?'+':''}{pct(perf?.pnl_pct)}</b></div><div className="chart-note">Estadísticas separadas por modo</div></div><div className="big-chart"><div className="chart-y"><span>{money(Math.max(...equity,1))}</span><span>{money((Math.max(...equity,1)+Math.min(...equity,0))/2)}</span><span>{money(Math.min(...equity,0))}</span></div><Sparkline values={equity}/><div className="chart-empty-overlay">{ops.closed.length===0&&<span>La curva {mode.toUpperCase()} aparecerá cuando existan operaciones cerradas.</span>}</div></div><div className="chart-legend"><span><i/>Capital {mode.toUpperCase()}</span><span>Operaciones y PnL del modo activo</span></div></article>
          <article className="panel performance-panel"><div className="panel-heading-row"><h3>Rendimiento {mode.toUpperCase()}</h3><span>Solo {mode.toUpperCase()}</span></div><div className={`hero-pnl ${(perf?.pnl||0)>=0?'green':'red'}`}>{(perf?.pnl||0)>=0?'+':''}{pct(perf?.pnl_pct)}<small>PnL acumulado <b>{money(perf?.pnl)}</b></small></div><Sparkline values={equity}/><div className="capital-boxes"><StatCard label="Capital inicial" value={money(perf?.capital)}/><StatCard label="Capital actual" value={money(perf?.current_capital)}/></div><div className="metric-grid"><StatCard label="Operaciones" value={perf?.trades||0}/><StatCard label="Win rate" value={pct(perf?.win_rate)} tone="green"/><StatCard label="Profit factor" value={(perf?.profit_factor||0).toFixed(2)}/><StatCard label="Drawdown máx." value={`-${pct(perf?.drawdown)}`} tone="red"/></div></article>
        </section>
        <section className="bottom-grid" id="operaciones"><article className="panel active-ops"><div className="panel-heading-row"><h3>Operaciones Activas · {mode.toUpperCase()}</h3><span className="green">{ops.open.length} {ops.open.length===1?'operación':'operaciones'}</span></div>{ops.open.length?ops.open.slice(0,3).map(p=><OpenPosition key={String(p.position_id||Math.random())} p={p}/>):<Empty text={`No hay posiciones ${mode.toUpperCase()} abiertas en este momento.`}/>}</article><article className="panel recent-ops"><div className="panel-heading-row"><h3>Últimas Operaciones · {mode.toUpperCase()}</h3><span>{ops.closed.length} cerradas</span></div>{ops.closed.length?<div className="ops-table"><div className="ops-row ops-head"><span>Par</span><span>Tipo</span><span>Resultado</span><span>PnL</span><span>Fecha</span></div>{ops.closed.slice(0,6).map(p=>{const v=pnl(p);return <div className="ops-row" key={String(p.position_id||Math.random())}><strong>{symbol(p)}</strong><b className={side(p)==='LONG'?'green':'red'}>{side(p)}</b><span className={v>=0?'green':'red'}>{v>=0?'● WIN':'● LOSS'}</span><strong className={v>=0?'green':'red'}>{money(v)}</strong><span>{date(p.closed_at||p.created_at)}</span></div>})}</div>:<Empty text={`Las operaciones ${mode.toUpperCase()} cerradas aparecerán aquí.`}/>}</article><article className="panel distribution"><div className="panel-heading-row"><h3>Resumen del motor</h3><span>{ent?.live_state||'demo'}</span></div><div className="donut" style={{'--pct':`${Math.max(0,Math.min(100,perf?.win_rate||0))*3.6}deg`} as CSSProperties}><div><small>Win rate</small><strong>{pct(perf?.win_rate)}</strong></div></div><div className="summary-list"><span><i className="green-dot"/>Modo<b>{mode.toUpperCase()}</b></span><span><i/>CoinW<b>{verified?'Verificado':'Pendiente'}</b></span><span><i/>Mercados<b>Auto</b></span><span><i/>Acceso LIVE<b>{config?.live_allowed?'Sí':'No'}</b></span></div></article></section>
        <section className="referral-section" id="referidos"><article className="panel referral-panel"><div className="panel-heading-row"><div><h3>Programa de referidos</h3><span>Comparte tu código y gana días LIVE cuando tu referido compra su primer plan.</span></div><span>{referrals?.referred_count||0} referidos</span></div><div className="referral-code-box"><div><small>Tu código</small><strong>{referrals?.referral_code||'Cargando…'}</strong></div><button onClick={async()=>{const code=referrals?.referral_code;if(!code)return;const link=`${window.location.origin}/?ref=${encodeURIComponent(code)}`;try{await navigator.clipboard.writeText(link);setCopied(true);window.setTimeout(()=>setCopied(false),1800)}catch{setNotice(`Código de referido: ${code}`)}}}>{copied?'Copiado ✓':'Copiar enlace'}</button></div><div className="referral-stats"><StatCard label="Referidos" value={referrals?.referred_count||0}/><StatCard label="Recompensados" value={referrals?.rewarded_count||0} tone="green"/><StatCard label="Días LIVE ganados" value={referrals?.reward_days_total||0}/></div><div className="referral-rules"><strong>Recompensas actuales</strong><span>Plan de 15 días → <b>7 días LIVE</b></span><span>Plan de 30 días → <b>15 días LIVE</b></span></div><div className="referral-list">{referrals?.items?.length?referrals.items.slice(0,8).map((r,i)=><div key={`${r.user_id||i}`}><span>{r.phone_masked||'Usuario referido'}</span><span>{r.rewarded?`Recompensa: ${r.reward_days} días`:'Pendiente de primera compra'}</span><small>{date(r.created_at)}</small></div>):<div className="empty-state compact"><p>Todavía no tienes referidos. Comparte tu enlace personal para empezar.</p></div>}</div></article></section>
      </main><footer>DISCIPLINA <b>·</b> ESTRATEGIA <b>·</b> RESULTADOS <Brand compact/></footer>
    </div>
  </div>
}

function MarketChip({icon,label,status}:{icon:string;label:string;status:string}){return <div className="market-chip"><span>{icon}</span><div><strong>{label}</strong><small>{status}</small></div></div>}
function PanelTitle({icon,title,badge,badgeTone}:{icon:ReactNode;title:string;badge?:string;badgeTone?:string}){return <div className="panel-title"><span>{icon}</span><h3>{title}</h3>{badge&&<b className={`badge ${badgeTone}`}>● {badge}</b>}</div>}
function EngineMetric({label,value}:{label:string;value:string}){return <div className="engine-metric"><span>{label}</span><strong>{value}</strong></div>}
function Empty({text}:{text:string}){return <div className="empty-state"><span>◇</span><p>{text}</p></div>}
function OpenPosition({p}:{p:Position}){
  const tp1=p.tp1_price??p.tp1;
  const target=p.tp2_price??p.tp2??p.target_price??p.take_profit;
  const exposure=num(p.quantity)*num(p.entry_price);
  return <div className="open-position"><div className="position-top"><div><span className="asset-badge">◈</span><strong>{symbol(p)}</strong><b className={side(p)==='LONG'?'long':'short'}>{side(p)}</b></div><span>{p.settlement_pending?'Confirmando cierre':`${p.leverage||10}x`}</span></div><div className="position-grid"><span>Entrada<strong>{marketPrice(p.entry_price)}</strong></span><span>Precio actual<strong>{marketPrice(p.current_price)}</strong></span><span>PnL actual<strong className={num(p.unrealized_pnl)>=0?'green':'red'}>{money(p.unrealized_pnl)}</strong></span><span>Exposición<strong>{money(exposure)}</strong></span><span>Margen estimado<strong>{money(exposure/Math.max(num(p.leverage),1))}</strong></span></div><div className="position-progress"><i/></div><div className="position-bottom"><span>SL<strong>{marketPrice(p.stop_price??p.stop_loss)}</strong></span>{tp1!=null&&<span>TP1<strong>{marketPrice(tp1)}</strong></span>}<span>{tp1!=null?'TP2':'TP'}<strong>{marketPrice(target)}</strong></span></div></div>;
}
