from enum import Enum
class Direction(str,Enum): LONG='LONG'; SHORT='SHORT'; BULLISH='BULLISH'; BEARISH='BEARISH'; NEUTRAL='NEUTRAL'; CONFLICTED='CONFLICTED'
class Strategy(str,Enum): BREAKOUT_RETEST='BREAKOUT_RETEST'; LIQUIDITY_SWEEP='LIQUIDITY_SWEEP'; NO_TRADE='NO_TRADE'
class RegimeState(str,Enum): TRENDING='TRENDING'; RANGING='RANGING'; TRANSITION='TRANSITION'; CHOPPY='CHOPPY'; EXTREME='EXTREME'
